name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
          single-commit: true
          git-config-name: "build bot"
          git-config-email: ""
